/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 nike1.gltf 
Author: SofiaWolfie (https://sketchfab.com/SofiaWolfie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-tc-7900-sail-fb2de7469d4f43c1aba7f878ef935cce
Title: Nike TC 7900 Sail
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/nike1.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.108}>
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_grund} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.nike_logga} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.baksida_logga} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.framsida} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.verdel} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.framsida_vre} />
      </group>
      <group scale={0.108}>
        <mesh geometry={nodes.Object_24.geometry} material={materials.sko_sula_underdel} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.sko_sula_sida} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.sko_sula_framifrn} />
      </group>
      <mesh geometry={nodes.Object_5.geometry} material={materials.metall_svart} position={[0.067, 0.044, -0.048]} rotation={[-3.008, -0.005, -2.218]} scale={[-0.01, 0.01, 0.01]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.006']} scale={[0.11, 0.108, 0.108]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials['Material.001']} scale={0.108} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.Material} scale={0.108} />
      <mesh geometry={nodes.Object_15.geometry} material={materials['Material.003']} position={[0.017, 0.116, -0.112]} rotation={[0.045, -0.145, 0.007]} scale={[0.108, 0.108, 0.103]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.sula_insida} scale={[0.11, 0.108, 0.108]} />
    </group>
  )
}

useGLTF.preload('/nike1.gltf')
